name: 🚀 Ultimate Zero-Error Auto-Healing + Hidden Encrypted Backup + Self-Recovery

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  auto-commit-optimize-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 3️⃣ Install Tools
      - name: Install Tools
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y nodejs npm curl wget zip openssl || true
          for i in 1 2 3; do
            npm install -g html-minifier-terser clean-css-cli terser linkinator && break
            echo "⚠️ Install failed, retrying..."
            sleep 10
          done

      # 4️⃣ Optimize Files
      - name: Optimize Website Files
        run: |
          echo "⚡ Optimizing HTML, CSS, and JS..."
          find . -type f -name "*.html" -exec sh -c '
            for f; do
              html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true "$f" -o "$f" || true
            done
          ' sh {} +

          find . -type f -name "*.css" -exec sh -c '
            for f; do
              cleancss -o "$f" "$f" || true
            done
          ' sh {} +

          find . -type f -name "*.js" -exec sh -c '
            for f; do
              terser "$f" -c -m -o "$f" || true
            done
          ' sh {} +

          echo "✅ Optimization Completed!"

      # 5️⃣ Health Check (Zero-Error)
      - name: Website Health Check
        continue-on-error: true
        run: |
          echo "🔎 Checking local HTML files for broken links..."
          npx linkinator file://$(pwd) --recursive --silent > health_report.log || true
          echo "✅ Health check completed!"

      # 6️⃣ Detect Real Changes
      - name: Detect Real Changes
        id: detect_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "REAL_CHANGES=false" >> $GITHUB_ENV
            echo "⚡ No real changes detected. Skipping commit/push."
          else
            echo "REAL_CHANGES=true" >> $GITHUB_ENV
            echo "✅ Real changes detected."
          fi

      # 7️⃣ Auto Commit Changes
      - name: Auto Commit Changes
        if: env.REAL_CHANGES == 'true'
        run: |
          TZ='Asia/Tehran'
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "🚀 Auto Optimized Update | ${DATE}" || true

      # 8️⃣ Create Hidden Encrypted Backup
      - name: Create Hidden Encrypted Backup
        if: env.REAL_CHANGES == 'true'
        run: |
          echo "🔒 Creating hidden encrypted backup..."
          mkdir -p .github/backup
          git bundle create .github/backup/hidden-backup.bundle HEAD || true
          zip -j .github/backup/hidden-backup.zip .github/backup/hidden-backup.bundle
          openssl enc -aes-256-cbc -salt -in .github/backup/hidden-backup.zip -out .github/backup/hidden-backup.enc -k "${{ secrets.GITHUB_TOKEN }}"
          rm -f .github/backup/hidden-backup.bundle .github/backup/hidden-backup.zip
          git checkout -b hidden-backup || git checkout hidden-backup
          mv .github/backup/hidden-backup.enc .
          git add hidden-backup.enc || true
          git commit -m "🔒 Hidden Encrypted Backup" || true
          git push origin hidden-backup --force || true
          git checkout main

      # 9️⃣ Push Changes with Retry
      - name: Push Changes with Retry
        if: env.REAL_CHANGES == 'true'
        run: |
          ATTEMPT=1
          until git push origin HEAD:main; do
            if [ $ATTEMPT -ge 3 ]; then
              echo "⚠️ Push failed after 3 attempts. Changes are backed up on hidden branch."
              exit 0
            fi
            echo "⚠️ Push failed, retrying in 15s (Attempt $ATTEMPT)..."
            ATTEMPT=$((ATTEMPT+1))
            sleep 15
          done
          echo "✅ Push successful!"

      # 🔟 Auto Self-Recovery if Main is Broken
      - name: Auto Self-Recovery
        if: failure()
        run: |
          echo "⚡ Main branch seems broken. Attempting self-recovery..."
          git fetch origin hidden-backup || true
          git checkout main
          git pull origin hidden-backup || true
          git push origin main --force || true
          echo "✅ Self-Recovery from hidden encrypted backup completed!"

      # 1️⃣1️⃣ Cleanup Logs
      - name: Cleanup Logs
        run: |
          find . -type f -name "*.log" -delete || true
          rm -rf .github/backup || true

      # 1️⃣2️⃣ Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 1️⃣3️⃣ Upload artifact for deployment
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # 1️⃣4️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        continue-on-error: true

      # 1️⃣5️⃣ Done
      - name: Done
        run: echo "🎉 Ultimate Zero-Error Auto-Healing + Self-Recovery Finished!"
